version: '3'
services:
  dev:
    image: mcr.microsoft.com/vscode/devcontainers/base:latest
    volumes:
      - ..:/workspace
    command: sleep infinity
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    command: npm start